spring:
  # 选择加载不同环境的配置文件
  profiles:
    active: dev

# mybatis
mybatis:
  mapper-locations: classpath:mybatis-mappers/*.xml
  configuration:
    cache-enabled: true  #全局映射器启用缓存
    use-column-label: true  # 允许使用列标签代替列名
    default-statement-timeout: 25000 #数据库超过25000秒仍未响应则超时
    multiple-result-sets-enabled: true #对于未知的SQL查询，允许返回不同的结果集以达到通用的效果


logging:
  path: /data/template/logs